/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultatsImport } from './routes/_resultats'
import { Route as PronosImport } from './routes/_pronos'
import { Route as ResultatsResultatsCompetitionIdImport } from './routes/_resultats/resultats.$competitionId'
import { Route as PronosPronosCompetitionIdImport } from './routes/_pronos/pronos.$competitionId'

// Create/Update Routes

const ResultatsRoute = ResultatsImport.update({
  id: '/_resultats',
  getParentRoute: () => rootRoute,
} as any)

const PronosRoute = PronosImport.update({
  id: '/_pronos',
  getParentRoute: () => rootRoute,
} as any)

const ResultatsResultatsCompetitionIdRoute =
  ResultatsResultatsCompetitionIdImport.update({
    path: '/resultats/$competitionId',
    getParentRoute: () => ResultatsRoute,
  } as any)

const PronosPronosCompetitionIdRoute = PronosPronosCompetitionIdImport.update({
  path: '/pronos/$competitionId',
  getParentRoute: () => PronosRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pronos': {
      preLoaderRoute: typeof PronosImport
      parentRoute: typeof rootRoute
    }
    '/_resultats': {
      preLoaderRoute: typeof ResultatsImport
      parentRoute: typeof rootRoute
    }
    '/_pronos/pronos/$competitionId': {
      preLoaderRoute: typeof PronosPronosCompetitionIdImport
      parentRoute: typeof PronosImport
    }
    '/_resultats/resultats/$competitionId': {
      preLoaderRoute: typeof ResultatsResultatsCompetitionIdImport
      parentRoute: typeof ResultatsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PronosRoute.addChildren([PronosPronosCompetitionIdRoute]),
  ResultatsRoute.addChildren([ResultatsResultatsCompetitionIdRoute]),
])

/* prettier-ignore-end */
