services:
  reverse-proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
      - backend
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    restart: always

  webapp:
    build:
      context: ../../apps/front/
      dockerfile: Dockerfile
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
    restart: always

  backend:
    build:
      context: ../../apps/back/
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/var/log/apps/
    environment:
      - NODE_ENV=development
      - TZ=UTC
      - SESSION_DRIVER=cookie
      - PORT=80
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - LOG_FILE_PATH=/var/log/apps/adonisjs.log
      - APP_KEY=${APP_KEY}
      - PUBLIC_FRONT_URL=${PUBLIC_FRONT_URL}
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: always
  