name: "CD Pipeline"

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [CI Pipeline]
    types: [completed]
    branches: [main]

env:
  # DB
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}

  # BACKEND
  NODE_ENV: production
  APP_KEY: ${{ secrets.APP_KEY }}
  TZ: UTC
  PORT: 80
  HOST: 0.0.0.0
  SESSION_DRIVER: cookie
  LOG_LEVEL: info
  LOG_FILE_PATH: not-used
  PUBLIC_FRONT_URL: https://prono.tensaii.dev
  PUBLIC_BACKEND_URL: https://api.prono.tensaii.dev
  GOOGLE_CLIENT_ID: {{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: {{ secrets.GOOGLE_CLIENT_SECRET }}


jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script_stop: true
        envs: DB_HOST,DB_PORT,DB_USER,DB_PASSWORD,DB_DATABASE,NODE_ENV,APP_KEY,TZ,PORT,HOST,SESSION_DRIVER,LOG_LEVEL,LOG_FILE_PATH,PUBLIC_FRONT_URL,PUBLIC_BACKEND_URL,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET
        script: |
          source ~/.nvm/nvm.sh
          cd pronostic-gg
          git pull
          NODE_ENV=development pnpm install
          pnpm run db:migrations:run:force

          cd hosting/prod
          docker compose up -d --build --remove-orphans